name: Raspberry image CI Build
on: 
  workflow_dispatch:

jobs:
  rpi-image:
    name: "Build photobooth Raspberry image"
    runs-on: ubuntu-latest
    steps:
      - name: Update system
        run: |
          sudo apt update
          sudo apt upgrade -y
      - name: Checkout photobooth
        uses: actions/checkout@v3
        with:
          submodules: true
          path: photobooth
      - name: Checkout pi-gen
        uses: actions/checkout@v3
        with:
          repository: RPI-Distro/pi-gen
          path: pi-gen
      - name: Install pi-gen dependencies
        run: |
          cat pi-gen/depends | rev | cut -d: -f1 | rev | xargs sudo apt install -y
      # build image using pi-gen
      - name: Build PI image
        run: |
          cp photobooth/image_builder/raspberry/custom-pi-config pi-gen/config
          cp -R photobooth/image_builder/raspberry/stage-photobooth pi-gen/stage-photobooth
          chmod +x pi-gen/stage-photobooth/00-install-photobooth/00-run.sh
          chmod +x pi-gen/stage-photobooth/01-disable-usercreation/00-run.sh
          chmod +x pi-gen/stage-photobooth/02-disable-autologin/00-run.sh
          chmod +x pi-gen/stage-photobooth/prerun.sh
          cp photobooth/install-raspbian.sh pi-gen/stage-photobooth/00-install-photobooth/files/
          chmod +x pi-gen/stage-photobooth/00-install-photobooth/files/install-raspbian.sh
          cp photobooth/photobooth.desktop pi-gen/stage-photobooth/00-install-photobooth/files/
          cd pi-gen
          touch ./stage5/SKIP
          touch ./stage5/SKIP_IMAGES
          touch ./stage2/SKIP_IMAGES
          sudo ./build.sh
      - name: Debug 2
        run: |
          sudo apt install -y tree
          tree ./pi-gen/deploy/
      - name: Publish image
        uses: actions/upload-artifact@v3
        with:
          name: photobooth-raspberry-image
          path: ./pi-gen/deploy/image_*.zip
